# Generated by Django 4.2.4 on 2023-09-17 12:29

from django.db import migrations, models
import sapp.models.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp_hr', '0002_alter_applicant_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='about',
            field=tinymce.models.HTMLField(blank=True, null=True, serialize={'col_css_class': 'col-12'}),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='address',
            field=models.TextField(blank=True, max_length=128, null=True, serialize={'col_css_class': 'col-12'}),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='id_document_file',
            field=sapp.models.fields.FileField(blank=True, null=True, serialize={'col_css_class': 'col-12'}, upload_to='personnel'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='proof_of_residence_file',
            field=sapp.models.fields.FileField(blank=True, null=True, serialize={'col_css_class': 'col-12'}, upload_to='personnel'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=sapp.models.fields.FileField(blank=True, null=True, serialize={'col_css_class': 'col-12'}, upload_to='personnel'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='about',
            field=tinymce.models.HTMLField(blank=True, null=True, serialize={'col_css_class': 'col-12'}),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, max_length=128, null=True, serialize={'col_css_class': 'col-12'}),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_document_file',
            field=sapp.models.fields.FileField(blank=True, null=True, serialize={'col_css_class': 'col-12'}, upload_to='personnel'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='proof_of_residence_file',
            field=sapp.models.fields.FileField(blank=True, null=True, serialize={'col_css_class': 'col-12'}, upload_to='personnel'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='resume',
            field=sapp.models.fields.FileField(blank=True, null=True, serialize={'col_css_class': 'col-12'}, upload_to='personnel'),
        ),
    ]
