# Generated by Django 4.2.4 on 2023-09-19 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sapp_hr', '0003_contract_salary_alter_applicant_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sapp_hr.rank'),
        ),
    ]
